## Quiz

In [2]:
from bs4 import BeautifulSoup
import os
import pandas as pd

In [3]:
# List of dictionaries to build file by file and later convert to a DataFrame
df_list = []
folder = 'rt_html'
for movie_html in os.listdir(folder):
    with open(os.path.join(folder, movie_html)) as file:
        
        soup = BeautifulSoup(file, 'lxml')
        
        title = soup.find('title').contents[0][:-len(' - Rotten Tomatoes')]
        
        audience_score = soup.find('div', class_ = 'audience-score meter').find('span').contents[0][:-1]
        
        num_audience_ratings = soup.find('div', class_ = 'audience-info hidden-xs superPageFontColor')
        
        num_audience_ratings = num_audience_ratings.find_all('div')[1].contents[2].strip().replace(',', '')
        
        # Append to list of dictionaries
        df_list.append({'title': title,
                        'audience_score': int(audience_score),
                        'number_of_audience_ratings': int(num_audience_ratings)})
df = pd.DataFrame(df_list, columns = ['title', 'audience_score', 'number_of_audience_ratings'])

## Solution Test
Run the cell below the see if your solution is correct. If an `AssertionError` is thrown, your solution is incorrect. If no error is thrown, your solution is correct.

In [4]:
df_solution = pd.read_pickle('df_solution.pkl')
df.sort_values('title', inplace = True)
df.reset_index(inplace = True, drop = True)
df_solution.sort_values('title', inplace = True)
df_solution.reset_index(inplace = True, drop = True)
pd.testing.assert_frame_equal(df, df_solution)

In [5]:
df

,title,audience_score,number_of_audience_ratings
0,12 Angry Men (Twelve Angry Men) (1957),97,103672
1,12 Years a Slave (2013),90,138789
2,A Hard Day's Night (1964),89,50067
3,A Streetcar Named Desire (1951),90,54761
4,Alien (1979),94,457186
5,All About Eve (1950),94,44564
6,All Quiet on the Western Front (1930),89,17768
7,Apocalypse Now (1979),94,284606
8,Argo (2012),90,207373
9,Army of Shadows (L'Armée des ombres) (1969),94,7011
10,Arrival (2016),82,78740
11,Baby Driver (2017),89,48114
12,Battleship Potemkin (1925),85,18709
13,Bicycle Thieves (Ladri di biciclette) (1949),94,33723
14,Boyhood (2014),81,88478
15,Brooklyn (2015),87,45763
16,Casablanca (1942),95,355952
17,Citizen Kane (1941),90,157274
18,Dr. Strangelove Or How I Learned to Stop Worry...,94,208215
19,Dunkirk (2017),82,53555
20,E.T. The Extra-Terrestrial (1982),72,32313030
21,Finding Nemo (2003),86,33355673
22,Frankenstein (1931),87,41140
23,Get Out (2017),87,63837
24,Gone With the Wind (1939),93,292794
25,Gravity (2013),80,301261
26,Harry Potter and the Deathly Hallows - Part 2 ...,89,389431
27,Hell or High Water (2016),88,37738
28,High Noon (1952),89,25065
29,Inside Out (2015),89,133558
...,...,...,...
70,The Babadook (2014),72,37024
71,The Battle of Algiers (La Battaglia di Algeri)...,95,14267
72,The Big Sick (2017),90,23391
73,The Bride of Frankenstein (1935),87,24471
74,The Cabinet of Dr. Caligari (Das Cabinet des D...,89,27163
75,The Conformist (1970),91,8529
76,The Dark Knight (2008),94,1827436
77,"The Godfather, Part II (1974)",97,409574
78,The Godfather (1972),98,730433
79,"The Good, the Bad and the Ugly (1966)",97,238420
80,The Grapes of Wrath (1940),88,23954
81,The Jungle Book (2016),86,92856
82,The Last Picture Show (1971),90,13893
83,The Maltese Falcon (1941),91,57268
84,The Night of the Hunter (1955),90,24322
85,The Philadelphia Story (1940),93,46810
86,The Third Man (1949),93,53081
87,The Treasure of the Sierra Madre (1948),93,25627
88,The Wages of Fear (1953),95,8536
89,The Wizard of Oz (1939),89,874425
90,The Wrestler (2008),88,139795
91,Tokyo Story (Tôkyô monogatari) (1953),93,11325
92,Touch of Evil (1958),92,30867
93,Toy Story 2 (1999),86,998186
94,Toy Story 3 (2010),89,605098
95,Toy Story (1995),92,1107731
96,Up (2009),90,1201878
97,Vertigo (1958),93,101454
98,Wonder Woman (2017),90,112955
99,Zootopia (2016),92,98633

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
title                         100 non-null object
audience_score                100 non-null int64
number_of_audience_ratings    100 non-null int64
dtypes: int64(2), object(1)
memory usage: 2.4+ KB